tools/metric_providers/cpu/energy/RAPL/MSR/system/source.c
tools/metric_providers/cpu/time/cgroup/container/Makefile
tools/metric_providers/cpu/time/cgroup/container/source.c
tools/metric_providers/cpu/utilization/cgroup/container/Makefile
tools/metric_providers/cpu/utilization/cgroup/container/source.c
tools/metric_providers/memory/total/cgroup/container/Makefile
tools/metric_providers/memory/total/cgroup/container/source.c
tools/metric_providers/network/io/cgroup/container/Makefile
tools/metric_providers/network/io/cgroup/container/source.c

- Get user_id dynamically
- refactor rapl code so that the main loop is leaner
- use #define variables instead of booleans

Bugfixes rapl c improvements

---

tools/metric_providers/lm_sensors/source.c

Closes https://github.com/green-coding-berlin/green-metrics-tool/issues/54

Now errors and exits if there is a feature specified that doesn't exist

---

api/api.py
frontend/js/stats.js
tools/runner.py

No api data handling

---

tools/runner.py

72 boot providers one by one with notes displaying what was booted to see energy consumption overhead of reporters individually

---

README.md
api/api.py
config.yml.example
docker/compose.yml.example
docker/nginx/api.conf
docker/nginx/frontend.conf
frontend/compare-old.html
frontend/data-analysis.html
frontend/js/main.js
frontend/js/stats.js
frontend/multi-old.html
frontend/request.html
frontend/stats.html
lib/email_helpers.py
test/api/test_api.py

`.org` to `.berlin`
`:8000` to `:9142`

126 - Domain and port changes

---

api/api.py
frontend/index.html
frontend/js/index.js

Added branch to projects list

---

config.yml.example
tools/metric_providers/psu/energy/ac/powerspy2/metric-provider.py
tools/metric_providers/psu/energy/ac/powerspy2/powerspy2.py
tools/metric_providers/psu/energy/ac/powerspy2/provider.py

Fixes the confusion in https://github.com/green-coding-berlin/green-metrics-tool/pull/57 
Closes: #101 
Closes: #140

Changes the powerspy provider to return mJ

---

.github/actions/gmt-pytest/action.yml
.github/workflows/tests-bare-metal-dev.yml
.github/workflows/tests-bare-metal-main.yml
.github/workflows/tests-vm-dev.yml
.github/workflows/tests-vm-main.yml
lib/global_config.py
test/setup-test-env.py
test/test_runner.py
test/test_usage_scenario.py

updated tests and workflows to work with new refactor

164 tests update for refactor

---

frontend/ci.html
frontend/js/ci.js

The curl call to add data: `curl -X POST "http://api.green-coding.example:9142/v1/ci/badge/add/" -H 'Content-Type: application/json' -d '{"value":"12365","unit":"mJ","repo":"owner-name/test-repo","branch":"test_branch","workflow":"test-workflow","run_id":"2312315","project_id":""}'`
The URL: `http://metrics.green-coding.example:9142/ci.html?repo=owner-name%2Ftest-repo&branch=test_branch&workflow=test-workflow`
What it looks like:
I feel like this might not be 100% what we were aiming at, but I'm opening a PR to start a discussion :)

Graph for badges

---

install_linux.sh
install_mac.sh

I did not manage to trigger any warning that the issue mentions.
Please validate that the message is shown on Mac :)

Success message at the end of the install script

---

runner.py

See https://github.com/green-coding-berlin/green-metrics-tool/issues/182#issuecomment-1473557206 and https://github.com/green-coding-berlin/green-metrics-tool/issues/215

Changes volume mounts from -v to --mount bind

---

metric_providers/psu/energy/ac/ipmi/system/provider.py

I tested this code by running the IPMI script on the Blockheating server and copying the output to a `.csv` to use in a temporary `__main__` function

Convert IPMI reporter to Joules

---

api/api.py
api/api_helpers.py
runner.py
test/api/test_api_helpers.py
tools/save_notes.py

Project name is no longer clickable on the Project data/General tab
Neither is anything inside of the usage scenario tab
Notes are also escaped and don't create a link in the database, or frontend.
I used the Python builtin `html.escape()`, so no dependency got introduced.

XSS in frontend

---

config.yml.example
lib/error_helpers.py

1. Adds an error file option in the config
2. If the error file is not None in config, then writes the errors to the error file as well

Extend the error helper to log to file

---

lib/db.py
tools/phase_stats.py

Ok, opening this up as a draft, because it currently fails to enter the data into the database.
Reason being type difference - `phase_stats.value` is `bigint` and some of the measurements are coming in as floats.
Does it make sense to change it from `bigint` to `numeric` or to round the numbers coming in?

Refactor phase state to use `copy_from`

---

runner.py

A user recently had the issue that a "working compose file" was not working in the GMT.
Reason being that the containers were not on the same network.
At the moment we require users to explicitely put containers on the same network ... which was a decision by me in the beginning, but we confusingly do not document that anywhere :)
Since the advent of Didis code that we import compose.yml files this has become now problematic.
This PR adresses this issue by creating a default network, similar to docker compose, unlesse a container speficies explicitely otherwise.
Happy for your input.
@ribalba  Put you in as reviewer. Can you just proof read the code, no need to test run
@dan-mm : I made a branch and example application here to showcase what kind of usage_scenario should work: …

Default network creation

---

api/api.py
docker/structure.sql
frontend/js/stats.js
frontend/stats.html
lib/process_helpers.py
migrations/2023_06_03_logs.sql
runner.py

Hey @dan-mm 
In this feature branch I am introducing logging of the stdout to database for debugging.
I had to change the order of a function: `self.read_and_cleanup_processes()`
Will that conflict with the tests?

Stdout Logs display in Dashboard

---

api/api.py
frontend/css/green-coding.css
frontend/index.html
frontend/js/helpers/phase-stats.js
frontend/js/index.js

Data tables for dashboard

---

frontend/css/green-coding.css
lib/hardware_info.py

Docker version info is now added to the hardware-info;
Also squashed a bug that the additional parameters where not correctly included.

Docker version info

---

lib/process_helpers.py
runner.py
test/data/usage_scenarios/setup_commands_stress.yml
test/test_usage_scenario.py

Until now we are issueing commands by default in a 'sh' process.
Not every container has a shell though. So we make it optional. And also not the default, as this is rather confusing.

No default shell

---

frontend/js/index.js

Index page loads faster due to async DataTables and only on request

Index page loads faster due to async DataTables and only on request

---

api/api_helpers.py
docker/structure.sql
frontend/js/helpers/metric-boxes.js
frontend/js/helpers/phase-stats.js
migrations/2023_07_14_min_value.sql
tools/phase_stats.py

Added the min value to the statistics. Before we had only max

Added min value

---

frontend/compare.html
frontend/js/helpers/converters.js
frontend/js/helpers/phase-stats.js
frontend/js/stats.js

Instead of notifications we now show permanent warnings

Warnings in dashboard

---

lib/hardware_info.py

Network interfaces are now displayed in the machine view

Network interfaces hardware info

---

api/api.py
frontend/index.html
frontend/js/helpers/main.js
frontend/js/index.js
test/api/test_api.py

Index.js can now filter according to the passed URL params
This will be used for linking externally to the page and pre-filtering it, as we have quite some projects now.

Index.js now can filter by repo and filename

---

docker/requirements.txt
install_mac.sh
metric_providers/base.py
tools/jobs.py

Created this as a start for a discussion.

Adds the stdbuf to disable buffering

---

lib/error_helpers.py
metric_providers/network/connections/proxy/container/provider.py
metric_providers/powermetrics/provider.py

@ribalba I removed a comment from you that I think was outdated in the NetworkProxy. Correct?
Can you quickly check if it is also working on your mac and then merge it in?
I refactored your `pgrep` call a little. I think it is cleaner this way ...

Powermetrics is now checked if it runs already on the system

---

api/api.py

Currently the API does not always alert the admin in case of errors.
With a hotfix I have already integrated some more HTTP exceptions: https://github.com/green-coding-berlin/green-metrics-tool/commit/37a56fb84aea526fbe638062e502562c86864d4f
The result is atm that we are getting a lot of email noise from non-relevant malformed crawler requests.
This PR blocks all emails to requests like IP, reverse DNS PTR etc.
What is left to discuss is how we handle HTTP 400 errors, which are currently not triggered in the middleware, but the application code itself.

Adding email blocking for requests to non-configured domain

---

runner.py

Docker now logs the error of the build to the saved logs viewable in online dashboard

Docker error now appear in logs in more detail

---

install_linux.sh
lib/hardware_info_root.py

Added lshw output, as we had no info about PCI, GPU, etc. info before.
The command delivers output without out, but is more comprehensive as root

Added lshw to hardware_info_root

---

runner.py

Fix printing of container logs

---

tests/data/usage_scenarios/env_vars_stress.yml
tests/data/usage_scenarios/env_vars_stress_unallowed.yml
tests/data/usage_scenarios/env_vars_stress_unallowed_backtick.yml
tests/data/usage_scenarios/env_vars_stress_unallowed_dollar.yml
tests/data/usage_scenarios/env_vars_stress_unallowed_paren.yml
tests/test_functions.py
tests/test_usage_scenario.py

Needed to make another PR as the test pipeline currently has a hickup.
This includes the fix from @davidkopp here: https://github.com/green-coding-berlin/green-metrics-tool/pull/541
Also I added tests and changed the logic of the env vars checking.

Env vars numbers tests

---

runner.py

Make Docker image tags lowercase

---

api/api_helpers.py
api/main.py
config.yml.example
docker/structure.sql
frontend/js/helpers/main.js
frontend/js/status.js
frontend/status.html
lib/repo_info.py
migrations/2024_01_04_machines_status.sql
runner.py
tools/client.py

- Addd GMT Hash
- Added GMT Timestamp
- Added jobs processing scheme
- Color codes for availability instead of text
- Explanation for status codes
- API can now filter by machine_id and state

Status page improvements

---

api/api_helpers.py
config.yml.example
docker/structure.sql
frontend/js/status.js
metric_providers/lm_sensors/source.c
migrations/2024_01_05_base_temperature.sql
tools/client.py
tools/temperature.py

This PR removes the static sleeping feature of the Cluster and adds a a dynamic cooldown temperature

Temperature Baseline cooldown in client.py

---

api/api_helpers.py
docker/structure.sql
frontend/js/status.js
frontend/status.html
migrations/2024_01_12_configuration.sql
tools/client.py

Machine configuration status

---

lib/process_helpers.py
runner.py
tests/data/usage_scenarios/stress_detached_exit.yml
tests/data/usage_scenarios/stress_detached_failure.yml
tests/data/usage_scenarios/stress_detached_no_exit.yml
tests/test_usage_scenario.py

Detached processes had an error and could not be checked properly in error case.
This PR fixed that and also moves to returncode handling

Tests and better handling for detached process

---

config.yml.example

Updating Grid Intensity avergages according to https://ember-climate.org/insights/research/global-electricity-review-2023
Updating Embodied carbon values according to newer Boavizta average values: https://dataviz.boavizta.org/terminalimpact

Updated Ember Climate and Boavizta values

---

config.yml.example
lib/hardware_info.py
lib/system_checks.py
test-config.yml
tools/client.py

@ribalba I added a function call mechansim. How do you like it? Can it be leaner / more neat?

Dynanmic system checks

---

api/api_helpers.py
api/main.py
config.yml.example
docker/requirements.txt
docker/structure.sql
frontend/carbondb-details.html
frontend/carbondb-lists.html
frontend/carbondb.html
frontend/hog-details.html
frontend/js/carbondb-details.js
frontend/js/carbondb-lists.js
frontend/js/helpers/main.js
frontend/timeline.html
lib/db.py
migrations/2024_02_06_adds_carbondb.sql
requirements-dev.txt
requirements.txt
test-config.yml
tests/api/test_api.py
tests/setup-test-env.py
tools/carbondb_compress.py

This is the first version of the CarbonDB GMT implementation. 
I will push the data generator ASAP. There are still a few minor things to fix there.

Initial version of the carbonDB

---

.github/actions/gmt-pytest/action.yml
install_linux.sh
install_mac.sh

@dan-mm I introduced a new flag in the install script. does this also need to be set in the example application tests somewhere?

Added no_python flag and ported flags to mac

---

api/main.py
frontend/ci.html
frontend/js/ci.js
migrations/2024_03_23_eco-ci-performance-fix.sql

Eco-CI Frontend was experiencing long query times and also was fetching large amounts of data.
Implemented new matching DB indices and also made 30 day fetching default instead of all

Eco CI performance fix

---

api/api_helpers.py
tests/api/test_api.py

See discussion here https://github.com/green-coding-solutions/green-metrics-tool/pull/723

tiny changes

---

api/api_helpers.py
api/main.py
config.yml.example
docker/structure.sql
lib/email_helpers.py
lib/error_helpers.py
lib/job/base.py
lib/job/email.py
lib/job/run.py
migrations/2024_04_13_error_handling.sql
runner.py
test-config.yml
tests/lib/test_jobs.py
tools/client.py
tools/jobs.py
tools/timeline_projects.py
tools/validate.py

This PR modularizes the error handling.
Before we had the issue that emails were sent sync. If the email vendors fails the API would hang.
This PR refactores the old jobs table to a proper versatile queuing mechanism. Run and Email are now implemented again.

Error handling modular

---

optimization_providers/durations/container.py
optimization_providers/resources/utilization.py
runner.py

Open sourcing basic optimizations that can also be usefully run in a non-cluster environment

Basic optimizations

---

tools/client.py

This PR adds a temperature gate to the cluster.
Before it was only validated that the machine is cool enough, aka back again at it's baseline temperature.
However since machines can also be in sleep and only be awakened for a measuremet they might cool down so low that it will distort the start of the measurement.
We deem this range to be 5° and will warm a machine up if that threshhold is reached.
Warmup is done though a spin-lock style loop.

Warmup for machines added if too cool

---

install_linux.sh
install_mac.sh
lib/hardware_info.py
lib/hardware_info_root_original.py
lib/system_checks.py
runner.py

RAPL energy filtering register is now checked.
Mechanism is achieved through allowing requests to the hardware_info_root file which has sudoers rights

Rapl energy filtering check

---

lib/schema_checker.py

I decided not to auto set it as the user might not want this behaviour.

Checks if when read-sci-stdout is specified that also log-stdout is True

---

api/main.py
config.yml.example
test-config.yml

This makes the CORS origins for the API dynamically extendable through the configuration

CORS allowed origins now dynamic

---

api/api_helpers.py
lib/db.py
lib/diff.py
lib/utils.py
tests/api/test_api.py
tests/lib/test_jobs.py
tools/timeline_projects.py

Removing need to understand what a psycopg dict_row is and just calling the associative fetch mode "dict"

Fetch mode named digestable

---

install_linux.sh
install_mac.sh

I don't have a Windows system to test this on. But apparently WSL returns  "Linux" in WSL 1 and WSL 2

Adds checks to the install scripts

---

.gitignore
tools/import_backup.sh

A script to import backups in .sql format

Added Backup script [skip ci]

---

api/api_helpers.py
lib/phase_stats.py
runner.py
test-config.yml
tests/metric_providers/test_metric_providers.py
tools/rebuild_phase_stats.py

The embodied carbon was missing as SCI was not correctly transported to the runner.
This PR re-introduces this transport, adds tests and also fixes the `rebuild_phase_stats.py` script to now respect SCI

Missing embodied carbon values

---

frontend/compare.html
frontend/css/green-coding.css
frontend/js/ci.js
frontend/js/helpers/charts.js
frontend/js/helpers/metric-boxes.js
frontend/stats.html

Adds CSS styles to frontend so that charts are always printed on one page

(feature): Print CSS styles for frontend [skip ci]

---

metric_providers/cpu/energy/rapl/msr/component/Makefile
metric_providers/cpu/time/cgroup/container/Makefile
metric_providers/cpu/time/cgroup/system/Makefile
metric_providers/cpu/time/procfs/system/Makefile
metric_providers/cpu/utilization/cgroup/container/Makefile
metric_providers/cpu/utilization/mach/system/Makefile
metric_providers/cpu/utilization/procfs/system/Makefile
metric_providers/disk/io/cgroup/container/Makefile
metric_providers/disk/io/procfs/system/Makefile
metric_providers/disk/used/statvfs/system/Makefile
metric_providers/lmsensors/Makefile
metric_providers/memory/energy/rapl/msr/component/Makefile
metric_providers/memory/used/cgroup/container/Makefile
metric_providers/memory/used/procfs/system/Makefile
metric_providers/network/io/cgroup/container/Makefile
metric_providers/network/io/procfs/system/Makefile
metric_providers/psu/energy/ac/mcp/machine/Makefile
metric_providers/psu/energy/dc/rapl/msr/machine/Makefile

-o is for output file -O is for optimisations

Fixes wrong o vs. O parameter

---

metric_providers/memory/used/procfs/system/source.c
metric_providers/network/io/cgroup/container/source.c
metric_providers/network/io/procfs/system/source.c

fixes the GCC warnings

---

.devcontainer/on-start.sh
.devcontainer/splash.md
.devcontainer/troubleshooting.md
.devcontainer/workshop/codespace-setup.sh
.devcontainer/workshop/devcontainer.json
.gitignore

- Fix runner command for example application in quickstart
- Add VS Code extensions
- Open markdown files in preview mode by default
- Ensure ports are set to public after Codespace restart
- Ignore backuped Makefile in Git
- Improve quickstart and add troubleshooting information

Improve Codespaces Setup

---

frontend/authentication.html
frontend/js/authentication.js

(feature): Added logout button

---

tools/prune_db.py

This PR fixes the script `tools/prune_db.py` to be able to remove failed runs or remove all measurement data.

Fix script prune_db.py

---

lib/scenario_runner.py
lib/system_checks.py

This PR checks if during a measurement the suspend state has been active

Suspend check

---

lib/notes.py
lib/scenario_runner.py
tests/data/usage_scenarios/stress_sci_multi.yml
tests/lib/test_phase_stats.py
tests/lib/test_save_notes.py
tests/test_functions.py
tests/test_runner.py
tests/test_yml_parsing.py

This PR uses a simplified log parsing system which operates on the full string and not on line by line regex matching

Log parsing on full data

---

lib/phase_stats.py
tests/lib/test_phase_stats.py

Discussion and reasoning here: https://github.com/green-coding-solutions/green-metrics-tool/issues/1239
Thanks @davidkopp

Remove network from sci

---

api/main.py
docker/structure.sql
frontend/cluster-changelog.html
frontend/cluster-status-history.html
frontend/cluster-status.html
frontend/css/green-coding.css
frontend/js/cluster-changelog.js
frontend/js/cluster-status-history.js
frontend/js/cluster-status.js
migrations/2025_09_20_cluster_health.sql

Introducing cluster status messages that can be added by an administrator to the DB.
Also showing cluster changelog and cluster status history in a new view

Added cluster status message, changelog and status history

---

api/main.py

This PR helps with debugging failed API requests.
ATM the output looks like this when somehting fails:
```text
Client (NoneType): None
Headers (MutableHeaders): MutableHeaders({'host': '[api.green-coding.io](http://api.green-coding.io/)', 'x-real-ip': '2003:c7:3742:400:c91e:78f9:e32d:f1b', 'x-forwarded-for': '2003:c7:3742:400:c91e:78f9:e32d:f1b', 'x-forwarded-proto': 'https', 'connection': 'close', 'sec-ch-ua-platform': '"macOS"', 'x-authentication': '****OBFUSCATED****', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36', 'sec-ch-ua': '"Not;A=Brand";v="99", "Brave";v="139", "Chromium";v="139"', 'sec-ch-ua-mobile': '?0', 'accept': '*/*', 'sec-gpc': '1', 'accept-language': 'de-DE,de;q=0.5', 'origin': …
```

Showing name and ID instead of only obfuscated info for user token
