green-coding-solutions/green-metrics-tool

test/data/usage_scenarios/basic_stress.yml
test/data/usage_scenarios/basic_stress_w_import.yml
test/data/usage_scenarios/cmd_stress.yml
test/data/usage_scenarios/env_vars_stress.yml
test/data/usage_scenarios/import_two_root.yml
test/data/usage_scenarios/network_stress.yml
test/data/usage_scenarios/port_bindings_stress.yml
test/data/usage_scenarios/setup_commands_multiple_stress.yml
test/data/usage_scenarios/setup_commands_stress.yml
test/data/usage_scenarios/volume_bindings_stress.yml
test/stress-application/usage_scenario.yml

As mentioned in the changelog, I've added the description field to GMT as well.
I have a whole bunch of failing tests at the moment on the `blue-angel-compare` branch, but no longer any `Key error: 'description'` at least after this commit.
@dan-mm I don't know the details of `test/data/usage_scenarios/`, so I've added where it made sense to me. Could you please double check them?

Added description field to usage scenarios

---

frontend/index.html
frontend/js/index.js

Adds number of runs selected for comparison. Fixes #274 
1. If there are no selected runs, the button will just say `Compare.`
2. If there is 1 run selected, the button says `Compare: 1 Run`
3. Else it says `Compare: n Runs`

Adds number of runs selected for comparison

---

runner.py
test/stress-application/usage_scenario.yml

GMT is now able to handle usage scenarios where the image that was built can be reused.
Thx @ribalba for writing the `docker inspect` code unintentionally to make this PR possible :)

Multi image fix

---

lib/schema_checker.py
runner.py

Currently we have the 'version' in the `usage_scenario.yml`.
I advocate here to remove this as it is just confusing because it conflicts with the `docker-compose.yml` *version* which actually has a meaning.
The idea of having a *version* is that one can versionate the `usage_scenario.yml`. However the way we actually use it we never advance this number and since we now merge with a compose file this is more confusing than helpful and anyway overwritten by the `docker-compose.yml` in the merge process ...
@dan-mm ok? Tests should not be concerned I guess?
@ribalba remarks?

Removing version requirement

---

lib/process_helpers.py
runner.py

Buffer reads could have a deadlock if there was a lot written to stdout.
This is now migitated by using `subprocess.run()` if possible. If we must use `subprocess.Popen` we use `communicate()` to read the buffer non-blocking. This only works if we do not timeout the process but use that only for detached ones.

Non blocking buffer reads

---

.github/actions/gmt-pytest/action.yml
install_linux.sh

@dan-mm I added a functionality so that the system will be put on a `tmpfs` for the `/tmp` directory in the install script.
This parameter triggers an input dialog.
Could you please adapt tests and pipelines so that the new code will run and then merge it?

tmpfs can now be set in install script

---

api/api.py
config.yml.example

GMT now allows to suppress success emails for adding projects in case the action was done by the admin

No notify admin for own project add

---

docker/compose.yml.example

We are using Postgres 15 now.
Please see https://docs.green-coding.berlin/docs/installation/updating/#update-postgresql for migrating

Postgres 15

---

runner.py

This PR adds the functionality to use the `--docker-prune` switch.
Previously we only had the `--full-docker-prune` switch that would delete everything including images.
However for a cluster it is typically not helpful to always redownload public docker images. Thus this switch will keep all the images that are public and save energy here, while still keeping the measurement and building of images active that are custom via Dockerfiles.
Also unassociated build caches, networks volumes and stopped containers on the system are removed which poses no harm to the user, but prevents the disk from getting full.
The switch is not on by default, as docker also does not have it on by default. Reason being is that it also removes stopped containers, which is something that some users might not …

Safer docker prune for daily use

---

docker/Dockerfile-gunicorn

Gunicorn now logs access logs to STDOUT.
This means we can now `print()` in the API and the logs will show up in the container logs.

Gunicorn now logs access to stdout

---

lib/schema_checker.py
runner.py

This enables you to have a compose file in which you specify all services that might be used at some stage. You can disabale a service in your usage_scenario by setting it to None. So let's say you have two databases defined in your compose.yml `db1` and `db2`.  You can only use one by adding to your usage file but still include the compose.
```
services:
db2:
```

Enables empty services in the usage_scenario

---

api/api.py
api/api_helpers.py
config.yml.example
frontend/css/green-coding.css
frontend/js/helpers/metric-boxes.js
frontend/stats.html
metric_providers/base.py
runner.py
tools/jobs.py
tools/phase_stats.py

This branch introduces the capability to output a new metric: [Green Software Foundation SCI](https://sci-guide.greensoftware.foundation/)
The parts to derive the metric have to be defined in two places:
- The `usage_scenario.yml` (which sets the dimension *R_d*)
- The `config.yml`, which sets the machine specific parameters like *TE*, *RS* etc.
The actual ticks for the unit of work (*R*) are captured from the containers and processes STDOUT. This has to be activated by setting `log-stdout` and `read-sci-stdout` to **True**.
The metric will atm only be calculated for the **RUNTIME** phase and be shown in the Dashboard.
If an SCI was configured also the parameters will be shown in the *Measurements* Tab.
Future work will include making the SCI an actual metric_provider and thus allowing to …

SCI metric

---

frontend/js/helpers/charts.js
frontend/js/helpers/config.js.example
frontend/js/helpers/phase-stats.js
frontend/js/stats.js

The unit is now display directly on the axis instead of the header

Unit is now inside charts

---

lib/hardware_info.py

@ribalba Can you please check if this works on Fedora.
I was not sure if I should do `dnf list installed` or `rpm -qa`.
Also I hacked it into a bash query, which I think is nicer than doing it in python. Or did you plan already for a mechanism to make that if/else smoother in Python?
Demo Run with data: https://metrics.green-coding.berlin/stats.html?id=7b635c8e-5dbc-4bc2-b2c5-99d373cce558

Added python and system packages listing

---

config.yml.example
tools/client.py

So far we had only one sleep time, which was initially triggered for waiting when no job was available.
However the client also needs a time to sleep when a measurement succeeded

Client has now two distinguished sleep times

---

lib/hardware_info.py

according to timing problems outlined here: https://www.brendangregg.com/blog/2021-09-26/the-speed-of-time.html
The clocksource in Linux can be an extreme source of cost for reading from it. Since the GMT does a lot of timestamping for all its reporters we need to log it.
Usually linux sets `tsc` as the most performant clocksource (https://access.redhat.com/solutions/18627) 
However in cloud situations or VMs, where we often run, this situation can be different and virtualized or low-granular clocks are used.
To test the clocksource this script can be used:
```C
#include <time.h>
void main()
{
int rc;
long i;
struct timespec ts;
for(i=0; i<10000000; i++) {
rc = clock_gettime(CLOCK_MONOTONIC, &ts);
}
}
```
Once compiled one iterates and sets all the clocksources in …

Adding current clocksource in linux

---

runner.py

Instead of this:
```
####################################################################################
Please access your with the ID c0a0a5c8-efbf-4b1c-9549-1bbb1d3c260d
####################################################################################
```
The GMT now reports this:
```
####################################################################################
Please access your report on the URL http://metrics.green-coding.internal:9142/stats.html?id=c0a0a5c8-efbf-4b1c-9549-1bbb1d3c260d
####################################################################################
```
This makes it easier for very unexperienced users to understand that a website is attached to the GMT and where it was configured.

Adding report url instead of just ID

---

CITATION.cff

Closes https://github.com/green-coding-berlin/green-metrics-tool/issues/533
For now I have only added it to the GMT. We should remember to add a similar file to the other repos when they become "big"
Also I have opted for only including the "core" developers as authors as otherwise we would habe to modify the file every time someone contributes

Adds the citation file

---

.gitignore
install_mac.sh

- Hardware_info_root.py was not created on mac. But we need it for consistency, even if returns empty.
- lib/hardware_info_root.py was not in .gitignore, but should be
- macOS does not understand the *root* group. Leaving group as staff (default) but setting only read

Hardware info root mac

---

runner.py

Allow digits in env var keys

---

frontend/js/helpers/config.js.example

Since we get another value from powermetrics for Intel CPUs this must also be added to the config.js.example as an explanatory metric

Fix for Intel macs for GMT

---

tests/README.MD

README for running tests is missing some information.
E.g. installing `pytest` and `pydantic` is not sufficient. I think it makes sense to just install every dev dependency before running the tests.
This change was part of PR #556 that won't get merged.

Document tests dependencies

---

frontend/js/helpers/metric-boxes.js

Since we currently do not have auto-scaling for the key values to make them more consistent we have sometimes the case that a value is to small to show.
This introduces the hover functionality, so that at least the raw value can be seen

Hovering over a unit to see raw value

---

config.yml.example

See https://docs.green-coding.berlin/docs/measuring/best-practices/#15-use-non-standard-sampling-intervals-and-avoid-undersampling

Moving to 99 Hertz to avoid lockstep sampling

---

frontend/js/settings.js
frontend/js/stats.js
frontend/settings.html
frontend/stats.html

Loading of a complex detailed measurements page can take enormous amounts of time du to the large amount of data transferred and the long query in the database.
Since this value cannot really be brought down, it is already compressed and DB indices are set, this PR shall enable the option to make the data transfer optional.
Especially beginner users do not need the timeline charts and rather use the phase_stats.
See the timing from the developer console attached. The PR brings this down to 10%

Make loading of detailed measurements optional

---

runner.py
tests/test_functions.py

Fixes #554
I have chosen the option to disable the Docker CLI hints via the environment variable `DOCKER_CLI_HINTS=false` in the current session.
Another option could be to permanently disable them in the Docker settings (`$HOME/.docker/config.json`):
```json
"plugins": {
"-x-cli-hints": {
"enabled": "false"
}
}
```

Disable Docker CLI hints

---

frontend/compare.html
frontend/stats.html

If there are many flows some of them are not visible and clickable in the frontend.
[Example measurement](https://metrics.green-coding.berlin/stats.html?id=b5478c99-c8b4-4f65-a25b-99180f5ced2f):
This PR adds the `wrapping` attribute to the menu ([→Fomantic docs](https://fomantic-ui.com/collections/menu.html#wrapping)).
Result:

Fix frontend flow menu to wrap automatically

---

frontend/js/helpers/config.js.example
frontend/js/helpers/metric-boxes.js

Changed wording for network infrastructure box

---

lib/hardware_info_root_original.py

Adds the RAPL powercapping information from the linux subsystem
```
drwxr-xr-x 6 root root    0 Dec 14 20:06 .
drwxr-xr-x 4 root root    0 Dec 14 20:06 ..
-r--r--r-- 1 root root 4.0K Dec 14 20:06 constraint_0_max_power_uw
-r--r--r-- 1 root root 4.0K Dec 14 20:06 constraint_0_name
-rw-r--r-- 1 root root 4.0K Dec 14 20:06 constraint_0_power_limit_uw
-rw-r--r-- 1 root root 4.0K Dec 14 20:06 constraint_0_time_window_us
-r--r--r-- 1 root root 4.0K Dec 14 20:06 constraint_1_max_power_uw
-r--r--r-- 1 root root 4.0K Dec 14 20:06 constraint_1_name
-rw-r--r-- 1 root root 4.0K Dec 14 20:06 constraint_1_power_limit_uw
-rw-r--r-- 1 root root 4.0K Dec 14 20:06 constraint_1_time_window_us
````
Typical values include the TDP of the chip and currently set power limits

Added powercap info to hardware_info

---

.github/actions/gmt-pytest/action.yml

We have an issue where some external PR's will fail because they attempt to write to the gunicorn cache and recieve a 403 Forbidden error, failing the entire pipeline.
I think we want to keep the security restriction, but the pipeline should continue. So the buildx command itself will now always return a success. However the pipeline should fail if the buildx command fails for any other reason, so I capture the (real) exit code and build output and will still fail on anything that is not a 403 Forbidden.
Unfortunately I don't see a quick/easy way to limit this to just external PR's, and our tests failing on cache issues isn't necessarily desired behaviour anyways, so this is now the default behaviour on all test runs. This does mean if we do have actual cache permissions errors they will …

fix for issue where tests on external PR's will fail when attempting to write to cache

---

lib/schema_checker.py
runner.py

Support reading notes from services

---

runner.py

Commit https://github.com/green-coding-berlin/green-metrics-tool/commit/270463c3663b7f5689209f4d934d596bace45d70 by @ribalba lead to the following warnings:
```log
/home/david/green-metrics-tool/runner.py:964: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if stderr_read is not None and str(stderr_read) is not '':
/home/david/green-metrics-tool/runner.py:1098: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if stderr_read is not None and str(stderr_read) is not '':
```
This PR fixes it.

Fix check if stderr is empty

---

tests/test_usage_scenario.py

The tests functions use the function `run_until`
This does no automatic cleanup. We had a regression that the tests were not running anymore because the call was not guard claused.

Tests run_until must be guard-claused with cleanup routine

---

lib/schema_checker.py
runner.py
tests/data/test_cases/subdir_volume_loading/subdir/usage_scenario_subdir.yml
tests/data/usage_scenarios/cmd_stress.yml
tests/test_usage_scenario.py

For unclear reasons the native `command` service top level element in the `docker-compose` specification was implemented as `cmd` in the GMT.
This PR changes this.
https://docs.docker.com/compose/compose-file/compose-file-v2/#command
Note: documentation and example applications have also been changed

Switched from cmd to command

---

install_linux.sh

Tinyproxy was started as a service. We do not want that on our machines.

Disable tinyproxy systemd service

---

frontend/js/helpers/charts.js
frontend/js/timeline.js

Adds a StdDev display to the timeline charts that dynamically changes on Zoom

Added stddev to timeline

---

api/main.py
docker/requirements.txt
requirements-dev.txt

Since PR https://github.com/green-coding-berlin/green-metrics-tool/pull/632 was merged we now can add the reading of the body in the GMT on error case in the API.
This was not possible before as the stream was *consumed* and not available anymore after initial parsing of the middleware

Non-Blocking starlette body read

---

api/api_helpers.py
frontend/js/timeline.js
frontend/timeline.html

The GMT can now color in the Timeline view not only by the hash of the tested software, but also by the hash of the GMT itself.
This functionality is used to visually debug energy anomalies when trying to discern wether a change in the software or a change in the tool itself is causing an energy anomaly.
Also the hashes are made clickable in the note. A problem however is that the note itself cannot be clicked in the current form.
@ribalba Do you know of a way to make the note hovering persistent in eCharts?
Sorting GMT:
Sorting Software:

GMT color via own commit hash

---

metric_providers/cpu/frequency/sysfs/core/get-scaling-cur-freq.sh
metric_providers/cpu/frequency/sysfs/core/provider.py
metric_providers/psu/energy/ac/ipmi/machine/ipmi-get-machine-energy-stat.sh
tests/start-test-containers.sh
tests/stop-test-containers.sh

This PR adds bash guards as `set -euo pipefail`
Just to be safe:
@dan-mm Is there a problem adding these to the test-containers scripts that I might be missing?
@ribalba Is there a problem adding these to the cluster cleanup bash script that I might be missing?

Euo pipefail

---

CONTRIBUTING.md

Suggestion: I find it helpful to explicitly state that GMT wants to receive pull requests via forks. Since you can also create pull requests without a fork.

chore: add info about forking workflow for contributors

---

.gitignore
test-config.yml
tests/setup-test-env.py

Notes:
- only CpuUtilizationProcfsSystemProvider && PsuEnergyAcSdiaMachineProvider turned on at the moment
- if we want, we can use PsuEnergyAcXgboostMachineProvider instead of PsuEnergyAcSdiaMachineProvider, either works (but not both)
- no changes needed for VM as these are the only providers that were running in the VM, but we no longer need to use the disable-metrics-provider script (the script itself is still in, just in case we ever want to use that functionality... but maybe cleanup would be preferred?)
- example applications will need a small update after merge in order to call the GMT-pytest action correctly (without disable script)
- no changes to test-compose.yml or structure.sql (they are also copied). 
- for test-compose.yml, that is because it copies from compose.yml.example …

standardized test-config

---

api/api_helpers.py
api/main.py
docker/structure.sql
frontend/js/helpers/runs.js
frontend/js/stats.js
migrations/2024_03_19_failed.sql
runner.py

Before the GMT could not distinguish between a run in progress and a failed run.
Under certain circumstances it can still happen that a run has failed but will show as in progress: When the run starts then fails but the DB also disconnects and the failed state cannot be saved to the database.
This we accept, although it could be fixed by an additional cleaning job that scans the run queue and sets all non-failed jobs that have not ended but are not running to failed

Added failed run visiblity

---

config.yml.example
docker/requirements.txt
docker/startup_gunicorn.sh
lib/db.py
lib/system_checks.py
requirements.txt

The easiest way is to use the implemented psycopg_pool class which implements dynamic retry times with increasing wait times: https://www.psycopg.org/articles/2021/01/17/pool-design/
Since we have no async or mutli-processing code the pool has no further advantage. I still opted for two connections open to have a failover
The pool itself is not opened through a context manager to have the connections be reused
Furthermore all rollback and error handling code has been removed, as the context manager takes care of this. The error only bubbles if the retry count of 30 seconds is exceeded.
Using this mechanic can be problematic for a benchmarking tool in the first place and allows us only to make DB connections when NO benchmarking is happing, which means in between any actual measurement …

DB Auto Reconnect on connection drop

---

docker/Dockerfile-gunicorn

This introduces the *new* buildx caching mechanism that even allows caches between builds and is outside of the layer caching.
Effectively now python packages will be cached and do no need to be redownloaded when building the gunicorn container for production or testing. Only if packages are updated.
What I did not introduce is to map it also to the OS cache, so it means that when we upgrade pandas it will still be downloaded 2 times. For the host OS install and for the docker container.
I found this to be more sane as otherwise I had to mount an external volume into the container which seems possible, but I could not get it working directly as it is outside of the build context in ../venv ... maybe a fix for a future improvement

Caching pip packages betweeen docker builds

---

install_linux.sh
install_mac.sh
requirements-dev.txt
requirements.txt

orjson is a requirement since the optimizations were introduced for the normal runner.py too.
Currently we only install it through `requirements-dev.txt` 
Since our unit tests install this file this dependency issue was not spotted.
This PR normalizes the install by not having functional requirements in the `requirements-dev.txt` but only such needed for pure testing.
Additionally all functional requirements for API includes are now fully installed to reduce complexity as a tradeoff for unneeded install on non-API machines (measurement nodes)

orjson requirement added

---

metric_providers/cpu/frequency/sysfs/core/get-scaling-cur-freq.sh
metric_providers/cpu/frequency/sysfs/core/provider.py
metric_providers/gpu/energy/nvidia/smi/component/README.md
metric_providers/gpu/energy/nvidia/smi/component/metric-provider-nvidia-smi-wrapper.sh
metric_providers/gpu/energy/nvidia/smi/component/provider.py
metric_providers/psu/energy/ac/ipmi/machine/ipmi-get-machine-energy-stat.sh
metric_providers/psu/energy/ac/ipmi/machine/provider.py
metric_providers/psu/energy/dc/rapl/msr/machine/README.md

Some reporters where using `-i 0.1` to sleep for 100 ms and some `-i 100` to sleep for 100 ms
This is now normalized.
The initial design decision was to to the least amount possible in the reporters in terms of conversion when collecting data. However we could not measure any difference in energy or time when using the non-conversion approach. So we opted for better consistency.

Normalized -i switch to always be ms

---

metric_providers/base.py

Metric reporters will here always be placed on core 0.
Making this CPU pinning decreases system energy use through the fact that the other cores can stay in deeper C-States.
Following scripts illustrate the concept:
```bash
#!/bin/bash
set -euo pipefail
pgrep -f metric_providers | xargs kill -9
taskset -c 0 ~/green-metrics-tool/metric_providers/cpu/energy/rapl/msr/component/metric-provider-binary -i 10 > /tmp/cpu-read &
taskset -c 0 ~/green-metrics-tool/metric_providers/memory/energy/rapl/msr/component/metric-provider-binary -i 10 > /tmp/memory-read &
taskset -c 0 ~/green-metrics-tool/metric_providers/psu/energy/dc/rapl/msr/machine/metric-provider-binary -i 10 > /tmp/psys-read &
taskset -c 0 ~/green-metrics-tool/metric_providers/psu/energy/dc/rapl/msr/machine/metric-provider-binary -i 10 …
```

Added taskset directive

---

runner.py

Provided path can already be a symbolic link, but not a local URI. This PR fixes this.

Allow local URI to be a symbolic link

---

config.yml.example

I'm currently adding the healthcheck feature to my microservices reference application.
Compose file: https://github.com/t2-project/devops/blob/main/energy-tests/gmt/microservices-compose.yml
Unfortunately, the configured 20 second wait time for dependencies is not sufficient on my machine. The `inventory` service (Spring Boot) needs more than 20 seconds to become healthy.
Of course on my local machine I can change the config on my own. However, that would not be possible using the measurement cluster.
An workaround is to use a sleep in `setup-command`, how I did it already in the past without the healthcheck feature.
I think it makes sense to increase the configured default wait time for dependencies, because 20 seconds seems to be too short for some Spring Boot applications in a …

Proposal: Increase default wait time for dependencies

---

lib/schema_checker.py
runner.py
tests/data/usage_scenarios/healthcheck.yml

This PR superseeds https://github.com/green-coding-solutions/green-metrics-tool/pull/780 and adds more str conversion for parameters that are allowed as `int` but must be `str` due to the nature of GMT shell outs.
Also some comments are added for clarity.
P.S.: This behaviour might be obsolte if we switch to an API based docker container orchestration contrary to the CLI atm

Moving int to str

---

docker/requirements.txt
docker/startup_gunicorn.sh

uvicorn.workers was deprecated. Moving to new class
Source: https://github.com/encode/uvicorn/pull/2302

Uvicorn worker

---

lib/schema_checker.py
runner.py
test-config.yml
tests/data/slow-start-application/Dockerfile
tests/data/slow-start-application/start.sh
tests/data/usage_scenarios/healthcheck_error_container_unhealthy.yml
tests/data/usage_scenarios/healthcheck_error_max_waiting_time.yml
tests/data/usage_scenarios/healthcheck_missing_start_period.yml
tests/data/usage_scenarios/healthcheck_using_interval.yml
tests/data/usage_scenarios/healthcheck_using_start_interval.yml
tests/test_usage_scenario.py

As discussed in #781 this PR implements the healthcheck parameter `start-interval`. In addition to that the logging around the healthcheck functionality is improved.
After some testing I came to the conclusion, that it is sufficient to just check every second what the health of the dependent container is without any additional logic.
There are 3 possible outcomes:
- container health becomes `healthy` -> pass
- container health becomes `unhealthy` -> exception
- configured max waiting time is reached -> exception
As proposed in #781 the default max waiting time should be increased (20 seconds is too short).
A compose file using the `start-interval` parameter can be found [here](https://github.com/t2-project/devops/blob/main/energy-tests/gmt/microservices-compose.yml). Currently, I have …

Improve Healthcheck with start-interval parameter

---

api/main.py
frontend/ci-index.html
frontend/css/green-coding.css
frontend/js/ci-index.js
frontend/js/helpers/main.js
frontend/js/repositories.js
frontend/repositories.html

CI Runs and Measurement runs can now be sorted by date and show directly when the last run happened.
Since the list became quite long this feature is needed for us to have an overview quickly which repos are active and receiving current runs.
Also sorting by name was made optional through an extra button

Added sorting by date and unified ci and measurement runs frontend

---

frontend/js/helpers/metric-boxes.js
tools/phase_stats.py

Adding the network CO2 to the calculation of the SCI.
Before network CO2 was treated separately. After a conversation with @mrchrisadams we decided to add it to the default SCI calculation and also make this more clear through a documentation page.
Clicking on "see details" next to the value brings you to https://docs.green-coding.io/docs/measuring/sci/#formula where it is made clear what goes into the SCI.

Adding network to SCI and clarifications

---

frontend/js/helpers/config.js.example
tools/phase_stats.py

This PR brings a power estimation feature per container to the GMT.
The approach is similar in it's idea on how Scaphandre does it:
- We use the CPU Utilization to derive a share of the containers given the total CPU Utilization of the system
- Different to Scaphandre we subtract the Idle power and thus only show the "overhead" that the containers have on the host system.
@mrchrisadams - Is that what you were looking for?
@davidkopp - Also would love your feedback on this as we have talked about this before.
A bit more context: Initially the philosphy of the GMT is not to have these values in as they provide limited insights. We have written are more detailed piece on this here: 
- https://docs.green-coding.io/docs/prologue/philosophy-methodology/#granularity-of-energy-data
- …

Power per container

---

api/api_helpers.py
tools/carbondb_remove_dubplicates.py
tools/carbondb_remove_duplicates.py

I went for a KISS version which needs to be called via `cron`. As we will be reworking carbonDB soonish I didn't want to do something overly complex like copying DBs around. We can call this every `n` minutes. We could consider setting a flag in redis if something has changed but I think we should think about this bigger. Maybe we need a general queuing system like jobs. But more flexible. Not something I see vital for now though

Adds a script to remove carbonDB duplicates

---

config.yml.example
runner.py
test-config.yml
tests/data/usage_scenarios/invalid_image.yml
tests/test_config_opts.py
tests/test_functions.py
tests/test_usage_scenario.py

A global timeout is added to prevent jobs to run too long in cluster setups.
This is needed as GMT moves towards more unattended automation
closes https://github.com/green-coding-solutions/green-metrics-tool/issues/790
closes https://github.com/green-coding-solutions/green-metrics-tool/issues/23

Global timeout

---

runner.py

Kaniko could not create multi-stage images as the filesystem was mounted read only.
It will place images in the `/workspace` folder, which seems like a pre-set directory.
This PR mounts the repo into a `/tmp/repo` folder and mitigates this issue thus allowing multi stage builds

Kaniko enable multi-stage builds

---

frontend/ci.html
frontend/js/ci.js

This PR also normalizes the display of CO2eq values, smoothens the table styling a bit and fixes a slight error with the CPU util avg. It was calculating an average of averages, which can be slightly higher or lower and is inaccurate.
Also showing the count for the totals as all steps, not as all measurements as the table claims.

Co2eq totals and Co2i totals

---

tests/smoke_test.py

This PR is a wild one.
1. Somehow the pytest fixture command got lost in a prior change leading to a non-complete cleaning of the database. Thus some old runs could be in there.
2. The code in `test_usage_scenario.py::test_uri_github_repo_branch` was starting a run with a different branch and then checking if that run was in the DB.
Since we now use pytest's randomization feature it seems like it does "fix" the random number generator for every module.
I am not sure if that should be called poisoning ... as in the end it makes tests still random over time but repeatable for a specific instance. 
In any case it leads to the fact that `smoke_test.py` and also `test_usage_scenario.py::test_uri_github_repo_branch` will generate the same random name for the run when calling …

Calling fixture

---

lib/email_helpers.py

Inspired by https://www.zerocarbon.email/ I added an *Expires* header to our email logging option.
At the moment this does not much, as Email Service Providers are not deleting messages yet. But hopefully this is soon to come and we want the GMT to be prepared for this.
The logging mails are by design only transient. Having them auto-deleted after 7 days is very sensible

Expires header added to email

---

install_linux.sh
install_mac.sh
lib/hardware_info.py
lib/hardware_info_root_original.py
lib/system_checks.py
runner.py

It was possible to replace the `python3` interpreter at the venv location with a malicious file.
Since we were giving access to the interpreter via a sudoers entry this would open a privilege escalation.
It is recommended to update to the newest version of the GMT and just re-run the `install_linux.sh` or `install_mac.sh` file. The fix will be applied then.

Security fix for python interpreter replacement

---

runner.py
tests/data/usage_scenarios/depends_on_custom_container_name.yml
tests/test_usage_scenario.py

If `container_name` was used in a setup with `depends_on` the state and health check did not work. This PR fixes that by using the provided `container_name` in the check.
I also tried to improve the wording in the log messages regarding the terms "service" and "container".
Fixes #859

Fix using depends_on in conjunction with container_name

---

metric_providers/psu/energy/ac/ipmi/machine/ipmi-get-machine-energy-stat.sh

A never before seen behaviour happened on one machine where the output of IPMI became so large that it apparently filled a buffer and the pipe was closed prematurely so a `head -1` failed with SIGPIPE (124).
Using sed fixes it. Inspired by Stackoverflow: https://unix.stackexchange.com/questions/736743/getting-first-line-of-piped-output-sets-exist-status-141-which-fails-bash-script

head -1 could lead to SIGPIPE 124

---

lib/schema_checker.py

Flow names need to be unique. This is something we check while executing the flow but it will fail quite late, once the second flow name is encountered. This adds a check when parsing the yml file

Checks for duplicate flow names

---

metric_providers/cpu/energy/rapl/msr/component/source.c
metric_providers/cpu/time/cgroup/container/source.c
metric_providers/cpu/time/cgroup/system/source.c
metric_providers/cpu/time/procfs/system/source.c
metric_providers/cpu/utilization/cgroup/container/source.c
metric_providers/cpu/utilization/procfs/system/source.c
metric_providers/disk/io/cgroup/container/Makefile
metric_providers/disk/io/cgroup/container/README.md
metric_providers/disk/io/cgroup/container/provider.py
metric_providers/disk/io/cgroup/container/source.c
metric_providers/lm_sensors/source.c
metric_providers/memory/total/cgroup/container/source.c
metric_providers/network/io/cgroup/container/source.c

This PR adds a Disk I/O reporter.
To make it container agnostic the data is pulled directly from the `sysfs`. This needs the IO delegator to be set as specified in the documentation.
I am currently under the assumption that this controller is always active for docker in root mode, but will double check soon.
The approach here is similar to the other cgroup reading metric providers. However while crafting this the idea came up to actually split Input and Output and not supply the value as a cumulated number.
I see here two options:
- Making the reporter something like a base reporter that always reads everything and then only a part of the value gets extracted
- Making a shallow reporter that works like the SDIA or XGBoost one and actually relies on another reporter to be present on the …

Added DiskIO Reporter

---

docker/structure.sql
migrations/2024_08_26_carbondb_unique.sql
tools/carbondb_compress.py

The constraint for the uniqueness in CarbonDB was not looking at all relevant rows.
We had this already implemented on our live system but not backported it to the repository.
The implementation so far was however not respecting NULL values correctly. The new unique index now treats two NULL values as identical and will trigger now.
@ribalba Data volume is now down from 13 GB to 9 MB

Carbondb unique

---

lib/schema_checker.py
runner.py
tests/data/usage_scenarios/duplicate_phase_name.yml
tests/data/usage_scenarios/empty_container_name.yml
tests/data/usage_scenarios/empty_phase_name.yml
tests/data/usage_scenarios/invalid_phase_name.yml
tests/data/usage_scenarios/invalid_phase_name_runtime.yml
tests/data/usage_scenarios/none_container_name.yml
tests/lib/test_schema_checker.py
tests/test_usage_scenario.py

Moving a lot of checks from the runner to the tests.
Also including a more rigid phase check for an allowed syntax.
@ribalba Maybe this helps creating your PR for the frontend schema checker

Phase name check

---

api/api_helpers.py
api/main.py

@ribalba 
I am currently trying to investigate an error we are seeing with the API when adding CarbonDB entries alongside CI measurements.
```
File "/var/www/startup/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
return await dependant.call(**values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/www/green-metrics-tool/api/main.py", line 1300, in post_ci_measurement_add
carbondb_add(client_ip, [energydata], user._id)
File "/var/www/green-metrics-tool/api/api_helpers.py", line 762, in carbondb_add
co2_value = energy_kwh * carbon_intensity # results in g
~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 0_o >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Error: Error in API call - …
```

Raising errors and applying caching

---

api/object_specifications.py

Relates to: https://github.com/green-coding-solutions/green-metrics-tool/issues/907#issuecomment-2376039483

Makes the disk optional

---

docker/Dockerfile-gunicorn
docker/auxiliary-containers/gcb_playwright/Dockerfile
lib/install_shared.sh

Probably a fix only for me but on my horrible Telekom peering I am seeing constant issues with python package downloads ala:
`pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.`
This PR tries to combat that without hopefully any downsided for anybody else

pip timeouts and retries increased

---

frontend/js/timeline.js
frontend/timeline.html

The URL is now automatically changed through the JS history API everytime a new search criteria is put in and submitted.

Timeline has now bookmark functionality [skip ci]

---

api/main.py
frontend/ci.html
migrations/2024_05_19_carbondb.sql

I toyed around with CarbonDB over the weekend and we now have the solar panel in CarbonDB reporting!
- Panel: https://metrics.green-coding.io/carbondb-lists.html?company_uuid=20b269ce-cd67-4788-8614-030eaf5a0b47&tag=GCS%20HQ%20Solar%20Panel&tag=GCS%20HQ%20Solar%20Panel
- Company total: https://metrics.green-coding.io/carbondb-lists.html?company_uuid=20b269ce-cd67-4788-8614-030eaf5a0b47
I integrated it in that form that the resulting CO2e is negative. This is debateable, but gives us a better view on generation vs. consumption vs. reduction.
In any case: The sun is shining today and in the 1 hour I am working here we have already saved 5 g of CO2. Yay!
- Make clear in frontend which dimension the values have
- Updated compress constraints, as it can happen that machines switch their tags, …

Carbondb 2.0

---

metric_providers/disk/io/cgroup/container/source.c
metric_providers/disk/io/procfs/system/source.c
metric_providers/network/io/cgroup/container/source.c

With the big refactor for 1.0 a bug was introduced that makes the IO provider for Network accumulate rathern than just echo the value.
The reason was a missing initalization of a struct.
For concisement also the disk-io provider is refactored although it did not have this bug.

Fix: metric providers for IO where accumulating instead of echoing

---

frontend/js/settings.js
frontend/js/stats.js
frontend/settings.html

TImeline Charts have now a toggleable AVG in the settings.
Also it is now clearer that the AVG always shows the AVG of the selection and not of the phase currently looked at

Toggle for AVG in Timeline Charts

---

api/main.py
frontend/css/green-coding.css
frontend/js/helpers/runs.js

Timeline can now be quickly access from the Home or Repositories view even without knowing the URL or having a project listed in "Timeline View"

Quick Access for timeline added

---

config.yml.example
cron/client.py
lib/validate.py

This PR enhanches the Workload Validation when the GMT is run in cluster mode.
Previous only the relative STDDEV could be checked.
This was problematic as workloads that have close to zero network traffic and then by chance have because of network issues 2-3 more TCP packets will directly incur + 100% network traffic.
By using absolute values this can now be better controlled. 
Furthermore one can also make relative AND absolute values ... although this makes no sense for the network case in particular.
Also I added more providers to the recommended to check when operating such a cluster. Network and phase time have been added

Making Workload Validation also accept absolute values

---

.devcontainer/codespace-setup.sh
.gitignore

Some minor improvements on how some files are ignored by Git:
- Ignore `sgx_enable` in tools directory (is a copy of the submodule that gets created during install)
- Ignore all output files in `lib/c` (`/detect_cgroup_path.o` was not ignored)
- Because the exclusion of the lmsensors build happens now in `install_shared.py` if the argument `install_sensors` is set to false, the old workaround in `codespace-setup.sh` is not relevant anymore → ignore of `Makefile.bak` is not relevant anymore

Gitignore improvements

---

frontend/js/helpers/phase-stats.js

This adds a deeplink functionality to GMT in case you want to open a specific phase in the "stats" or "compare" view.
Example: https://metrics.green-coding.io/stats.html?id=1ec10430-a789-44c9-8f7e-c394fc708b25
=> This would always open the *Runtime* phase tab
- https://metrics.green-coding.io/stats.html?id=1ec10430-a789-44c9-8f7e-c394fc708b25#BASELINE
=> This would open the *Baseline* phase tab
- https://metrics.green-coding.io/stats.html?id=1ec10430-a789-44c9-8f7e-c394fc708b25#RUNTIME__Stress
=> This would open the *Runtime* phase tab with the *Stress* sub-phase

Allowing Deeplinks to specific phases [skip ci]

---

api/api_helpers.py
api/main.py
api_test.py
frontend/css/green-coding.css
frontend/js/ci.js
frontend/js/compare.js
frontend/js/helpers/charts.js
frontend/js/helpers/main.js
frontend/js/helpers/phase-stats.js
frontend/js/stats.js
frontend/js/timeline.js
frontend/timeline.html

This PR:
- Introduces new QoL feature to see in comparsion view which bar belongs to which run (See Screenshot)
- Refactors how phase display works. Before ALL phases and charts where rendered. In practice however in 90% of the cases only the *[RUNTIME]* phase is really looked at. Which means GMT is doing 90% waste compute for every frontend display. In larger runs this can take up to 10 seconds to render. This now renders phases on demand only

Clickable Comparsion Charts + Display Missing Values

---

api/api_helpers.py
frontend/js/helpers/converters.js
frontend/js/settings.js

This PR moves GMT to milli-watt-hours by default.
See Discussion: https://github.com/green-coding-solutions/green-metrics-tool/discussions/1132

Moving to milli-watt hours

---

frontend/js/helpers/charts.js
frontend/js/timeline.js

Was needed as often the relative StdDev is identical but in a different ballpark of absolute StdDev. This is misleading when just taking a quick glimpse.

Charts now display absolute StdDev

---

frontend/js/helpers/main.js

The `copyToClipboard` method had several issues:
- the alert command was unreachable, because it came after the return statement (therefore the warning "unreachable code after return statement" was displayed in the dev console)
- return value is not required, because the event listeners don't use return values for event handling
- the error message was wrong: the clipboard API is actually available locally, `localhost:9142` works, but not `http://metrics.green-coding.internal:9142`
- the clipboard API is async

Fix error handling for clipboard API is unavailable

---

lib/scenario_runner.py
lib/schema_checker.py

This is needed for the OpenCloud usage scenario

Adds labels and network aliases

---

lib/scenario_runner.py

I often create a `usage_scenario` in /tmp or somewhere to test something. Currently it is quite annoying that I need a git repo to run the tool. When I use `--dev-no-save` I don't technically need this data as we are not saving anything so we can skip it and we can enable "test" runs without git

Skips the git commands when dev-no-save is specified

---

tests/test-config-extra-network-and-duplicate-psu-providers.yml
tests/test-config.yml.example
tests/test_functions.py
tests/test_runner.py

I had issues running `tests/test_runner.py::test_template_website`. This PR fixes some issues related the test configuration.
Sometimes the test still fails because the squid container does not become healthy. Potential cause: the healthcheck makes requests to the external website http://example.com

Fix test execution of runner.py

---

config.yml.example
metric_providers/cpu/time/cgroup/container/source.c
metric_providers/cpu/time/cgroup/system/README.md
metric_providers/cpu/utilization/cgroup/container/README.md
metric_providers/cpu/utilization/cgroup/container/source.c
metric_providers/cpu/utilization/cgroup/system/README.md
metric_providers/disk/io/cgroup/container/source.c
metric_providers/disk/io/cgroup/system/README.md
metric_providers/memory/used/cgroup/container/source.c
metric_providers/memory/used/cgroup/system/README.md
metric_providers/network/io/cgroup/container/source.c
metric_providers/network/io/cgroup/system/README.md

Corresponding changes in documentation repo: https://github.com/green-coding-solutions/documentation/pull/117
Related to discussion in issue https://github.com/green-coding-solutions/green-metrics-tool/issues/1267
New metric providers in config.yml were tested successfully together with PR https://github.com/green-coding-solutions/green-metrics-tool/pull/1270, with one exception: the cgroup system network provider has an issue (I will create a new PR for that).

Document the usage of cgroup system metric providers

---

lib/c/Makefile
lib/c/detect_cgroup_path.c
metric_providers/cpu/energy/rapl/msr/component/Makefile
metric_providers/cpu/throttling/msr/component/Makefile
metric_providers/cpu/time/cgroup/container/Makefile
metric_providers/cpu/time/cgroup/system/Makefile
metric_providers/cpu/time/procfs/system/Makefile
metric_providers/cpu/utilization/cgroup/container/Makefile
metric_providers/cpu/utilization/cgroup/system/Makefile
metric_providers/cpu/utilization/mach/system/Makefile
metric_providers/cpu/utilization/procfs/system/Makefile
metric_providers/disk/io/cgroup/container/Makefile
metric_providers/disk/io/cgroup/system/Makefile
metric_providers/disk/io/procfs/system/Makefile
metric_providers/disk/used/statvfs/system/Makefile
metric_providers/gpu/energy/nvidia/nvml/component/Makefile
metric_providers/lmsensors/Makefile
metric_providers/memory/energy/rapl/msr/component/Makefile
metric_providers/memory/used/cgroup/container/Makefile
metric_providers/memory/used/cgroup/system/Makefile
metric_providers/memory/used/procfs/system/Makefile
metric_providers/network/io/cgroup/container/Makefile
metric_providers/network/io/cgroup/system/Makefile
metric_providers/network/io/procfs/system/Makefile
metric_providers/psu/energy/ac/mcp/machine/Makefile
metric_providers/psu/energy/dc/rapl/msr/machine/Makefile

Closes https://github.com/green-coding-solutions/green-metrics-tool/issues/1267
The change was tested successfully:
Between the two statements the binary was recompiled with the change introduced in this PR.
This PR includes changes to all Makefiles to add the missing dependency declarations. I had the problem, that re-compiling the metric-provider-binary lead to the message: "'metric-provider-binary' is up to date"
The changed `detect_cgroup_path.o` was not recognized due to the missing dependency declaration. I hope it is ok to include this change here. If not, let me know.

Detect systemd cgroup path using cgroup name (instead of container id)

---

docker/Dockerfile-gunicorn
docker/compose.yml.example
tests/data/bare-metal/Dockerfile
tests/data/bare-metal/README.md
tests/data/bare-metal/usage_scenario.yml
tests/data/bare-metal/usage_scenario_enterprise.yml

This PR introduces the functionality to test the unit-tests of GMT itself inside of a specially crafted [sysbox](https://github.com/nestybox/sysbox) container.
Tests can only be run when the *sysbox-runc* runtime is active for the docker host. See Readme for details

Bare metal tests sysbox

---

lib/scenario_runner.py
tests/data/usage_scenarios/network_host_create.yml
tests/data/usage_scenarios/network_host_join.yml
tests/test_usage_scenario.py

This PR addresses a potential security vulnerability in GMT.
Currently no check is done if the network that will be joined might have pre-defined elevated capabilities / is un-isolated.
To our knowledge this is only the case for the *host* network.
This PR restricts joining the network to `--allow-unsafe` use cases.
Furthermore creation of pre-defined networks is blocked (although docker-cli would also disallow it). But the error is nicer in GMT and we are unsure how other orchestrators in the future like podman handle this.
Joining the `bridge` network is to our understanding no security issue and thus allowed.

Blocking joining or creating pre-defined networks

---

lib/scenario_runner.py
lib/schema_checker.py
templates/website/compose.yml
templates/website/playwright-ipc.js
templates/website/usage_scenario.yml

This PR introduces the concept of having playwright commands directly in the usage scenario.
This was made based on an idea of @davidkopp 
To make the commands work we need IPC between playwright and GMT.
To make this low overhead we use native I/O blocking from the linux subsystem by creating two files:
- /tmp/playwright-ipc-ready 
- This is used to signal to GMT that playwright is ready for the next command
- /tmp/playwright-ipc-commands 
- This is used for playwright to ingest the command
The functionality is kept hidden from the user only exposing a simple string based YML syntax.
Example can be seen here: 
https://github.com/green-coding-solutions/branch-magazine-energy-tests/blob/2741f206385a5280bb275da1b5bf2db46f148185/usage_scenario_normal.yml#L66
@davidkopp How do you like this …

Playwright command

---

frontend/js/stats.js
lib/scenario_runner.py

This PR fixes 3 issues regarding the display of the note `pulling {image}` in the charts:
1. Remove unnecessary double-escaping of notes (was accidentally introduced by https://github.com/green-coding-solutions/green-metrics-tool/pull/1329)
2. Fix show actual pulled image name in notes
3. Add automatic text wrapping for long notes
Final result:

Fix note 'pulling image' in charts

---

config.yml.example
lib/scenario_runner.py
tests/test-config.yml.example

The revert was necessary bc images where saved always with the container registry as explicit information to the local image store
Due to this fact it was not possible anymore to have normal image names like "alpine". It would always show like "index.docker.io/library/alpine" and docker engine would not understand the equality to "192.168.xxx.xxx/library/alpine"
Since this is not a relevant feature for measuring locally, but just a cluster centric optimization we unbundle this functionality again from GMT, but we keep the option for kaniko to understand if the docker agent has a different registry set.

Revert docker container registry

---

frontend/js/settings.js

Minor fix: The checkboxes in the user settings were not reset to false after a reload if they were checked previously without saving.

Fix checkboxes reset in user settings

---

.github/actions/gmt-pytest/action.yml
.github/workflows/tests-vm-main.yml
.github/workflows/tests-vm-pr.yml
tests/test_runner.py

Add debug outputs to investigate issue #1360 
In addition to that it also introduces two new optional input variables for the CI pipeline:
- `test-path` -> let us specify a specific test that should be executed in the pipeline instead of all
- `enable-ssh` -> let us enable a ssh connection for debugging purposes
I also added the ability to run the PR workflow manually (`workflow_dispatch`).

Add debug outputs to investigate failing multi arch image test case
